/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'personal_budgeting';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CATEGORIES2 = 'assets/categories2.png';
  static const String ENTERTAINMENT = 'assets/images/Entertainment.jfif';
  static const String BILL = 'assets/images/bill.JPG';
  static const String BUDGET = 'assets/images/budget.png';
  static const String CATEGORIES = 'assets/images/categories.png';
  static const String ENTER = 'assets/images/enter.png';
  static const String EXPENSIVE = 'assets/images/expensive.png';
  static const String FLASH_DEAL = 'assets/images/flash_deal.png';
  static const String FOOD = 'assets/images/food.jpg';
  static const String HOME = 'assets/images/home.png';
  static const String LOGO = 'assets/images/logo.png';
  static const String SPLASH_LOGIN_REGISTRATION_BACKGROUND_IMAGE =
      'assets/images/splash_login_registration_background_image.png';
}
