/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String SANS_BOLD = 'sans_bold';
  static const String SANS_REGULAR = 'sans_regular';
  static const String SANS_SEMIBOLD = 'sans_semibold';
}
